# Generated by Django 2.2.5 on 2019-12-23 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='url',
            new_name='link',
        ),
        migrations.AddField(
            model_name='meal',
            name='category',
            field=models.CharField(choices=[('verduras', 'verduras'), ('pasta', 'pasta'), ('carne', 'carne'), ('especial', 'especial'), ('guiso', 'guiso'), ('postre', 'postre'), ('pescado', 'pescado')], default='pasta', max_length=264),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meal',
            name='complexity',
            field=models.CharField(choices=[('EASY', 'facil'), ('MEDIUM', 'medio'), ('DIFFICULT', 'dificil')], default='simple', max_length=264),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meal',
            name='duration',
            field=models.CharField(choices=[('short', 'corto'), ('medium', 'medio'), ('long', 'largo')], default='long', max_length=264),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meal',
            name='ingredients',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meal',
            name='is_new',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
