# Generated by Django 2.2.5 on 2020-12-24 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=264, unique=True)),
                ('category', models.CharField(blank=True, choices=[('verduras', 'verduras'), ('pasta', 'pasta'), ('carne', 'carne'), ('especial', 'especial'), ('guiso', 'guiso'), ('postre', 'postre'), ('pescado', 'pescado')], default='', max_length=264)),
                ('ingredients', models.TextField(blank=True)),
                ('complexity', models.CharField(blank=True, choices=[('EASY', 'facil'), ('MEDIUM', 'medio'), ('DIFFICULT', 'dificil')], default='', max_length=264)),
                ('duration', models.CharField(blank=True, choices=[('short', 'corto'), ('medium', 'medio'), ('long', 'largo')], default='', max_length=264)),
                ('link', models.URLField(blank=True, default='')),
                ('is_new', models.BooleanField(blank=True, default=True)),
                ('image_name', models.CharField(blank=True, default='', max_length=264)),
                ('image', models.ImageField(blank=True, upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Dates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('name', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='app.Meal')),
            ],
        ),
    ]
