# Generated by Django 2.2.5 on 2020-12-29 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cadeau',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[('Luka', 'Luka'), ('Alex', 'Alex'), ('David', 'David')], default='', max_length=264)),
                ('amount', models.IntegerField(choices=[(1, 1), (5, 5), (10, 10)], default='')),
            ],
        ),
    ]
