# Generated by Django 2.2.5 on 2019-12-23 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20191223_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='link',
            field=models.URLField(),
        ),
    ]
