# Generated by Django 2.2.5 on 2020-12-29 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_cadeau'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadeau',
            name='child',
            field=models.CharField(blank=True, choices=[('Luka', 'Luka'), ('Alex', 'Alex'), ('David', 'David')], default='', max_length=264),
        ),
        migrations.AlterField(
            model_name='cadeau',
            name='amount',
            field=models.IntegerField(choices=[(1, 1), (5, 5), (15, 15), (20, 20), (30, 30), (40, 40), (50, 50), (100, 100), (200, 200), (300, 300), (500, 500)], default=''),
        ),
        migrations.AlterField(
            model_name='cadeau',
            name='name',
            field=models.CharField(blank=True, choices=[('opa', 'opa'), ('tante Ria', 'tante Ria'), ('abuelos', 'abuelos'), ('otro', 'otro')], default='', max_length=264),
        ),
    ]
