# Generated by Django 2.2.5 on 2019-12-23 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20191223_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='image_name',
            field=models.CharField(default='image.jpg', max_length=264),
            preserve_default=False,
        ),
    ]
